"""seeking columns and fix relations

Revision ID: 1a2b27b355ef
Revises: 7282d19de854
Create Date: 2020-12-22 14:09:47.663864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b27b355ef'
down_revision = '7282d19de854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('seeking_shows', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'seeking_description')
    op.drop_column('artist', 'seeking_shows')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
